server:
  port: 8080
  # debug | release | test 运行环境
  level: debug

path: D:\lumin\GO\Project\takeout

datasource:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  db_name: sky_take_out
  config: charset=utf8mb4&parseTime=True&loc=Local

log:
  level: debug
  filepath: ./logger/systemLog.txt

jwt:
  admin:
    # 设置jwt签名加密时使用的秘钥
    secret: admin
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    name: token
  user:
    # 设置jwt签名加密时使用的秘钥
    secret: user
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    name: Authorization

alioss:
  endpoint: oss-cn-beijing.aliyuncs.com
  access_key_id: LTAI5tG76SY7EF5Cnwr9oYeM
  access_key_secret: bRbpNl4E7iRIc3SURmuO4nHZFODPZW
  bucket_name: asda1s3d2a1sd263asd1a3s654a65sd4a65
